name: LIVJOCELYN
favicon: null
layout_spectrum: 0.48949
typography_spectrum: 0.033113121753558517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f69c9b'
    - '#877bb9'
    - '#ffed81'
    - '#6acbde'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.8135185244027525
  rhythmicContrast: 0.4130321489647031
purpose: []
