name: JOCELYN ANNA L*LIVIN8LOVE
favicon: null
layout_spectrum: 0.77245
typography_spectrum: 0.033113121753558517
title: EYE TO THE WORLD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: ' 52.32.215.222'
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f69c9b'
    - '#877bb9'
    - '#ffed81'
    - '#6acbde'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.8135185244027525
  rhythmicContrast: 0.4130321489647031
purpose: []
